<?xml version="1.0" encoding="utf-8"?><Database Name="db_PetShop" Class="dbpetshopDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=DESKTOP-48CBQ99;Initial Catalog=db_PetShop;Integrated Security=True" SettingsObjectName="PetShop.Properties.Settings" SettingsPropertyName="db_PetShopConnectionString" Provider="System.Data.SqlClient" />
</Database>